name: Elemental
version: '${project.version}'
main: de.nerobuddy.elemental.Elemental
api-version: 1.18
commands:
  fly:
  gamemode:
  feed:
  heal:
  sethealth:
  godmode:
  uuid:
  nick:
  resetnick:
  afk:
  isafk:
  vanish: